version: '3.8'
services:
  first_node:
    environment:
      - PEERS=ws://second_node:6001,ws://localhost:3001
      - SECRET_KEY=x]vf4yp0yf
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3003:3001"
  second_node:
    environment:
      - PEERS=ws://first_node:6001,ws://localhost:3001
      - SECRET_KEY=x]vf4yp0yf
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3004:3001"